#include <stdio.h>
#include <unistd.h>

int	main(void)
{
	// printf("TESTING +\n");
	// // printf("%+c\n", 'a');
	// // printf("%+s\n", "test");
	// printf("%+d\n", 0);
	// printf("%+3d\n", 0);
	// printf("%+d\n", -1);
	// printf("%+d\n", 78);
	// printf("%+d\n", -101);
	// printf("%+i\n", 0);
	// printf("%+i\n", -1);
	// printf("%+i\n", 78);
	// printf("%+i\n", -101);
	// printf("%+u\n", 78);
	// printf("%+u\n", -101);
	// printf("%+x\n", 78);
	// printf("%+X\n", -101);
	// printf("%+p\n", 78);
	// printf("%+p\n", -101);
	// printf("%+%\n");
	// printf("\nTESTING 0\n");
	// printf("%01d\n", 0);
	// printf("%02d\n", -1); 
	// printf("%04d\n", -1); 
	// printf("%04d\n", 88);
	// printf("%03i\n", 14);
	// printf("%01u\n", -99);
	// printf("%05d\n", 17);
	// printf("%10x\n", -17);
	// printf("%05X\n", 100);
	// printf("%X\n", 100);
	// printf("%05p\n", 100);
	// printf("%15p\n", 100);
	// printf("%03c\n", 'c');
	// printf("%03s\n", "sa");
	// printf("%03%\n");
	printf("\nTESING .\n");
	// printf("%.s\n", "test");
	// printf("|%.3s\n", "t");
	// printf("%.6s\n", " - ");
	// printf("%.c\n", 'c');
	// printf("%.1c\n", 'c');
	// printf("%.6c\n", 'c');
	// printf("%.d\n", 0);
	printf("%.0d\n", 1);
	printf("%.1d\n", 1);
	printf("%.0d\n", 0);
	printf("%.1d\n", 0);
	printf("%.2d\n", -1);
	printf("%.2d\n", 9);
	// printf("%.3i\n", 101);
	// printf("%.4i\n", -100);
	// printf("%.3u\n", 11);
	// printf("%.4u\n", 14);
	// printf("%.5u\n", -8);
	// printf("%.1u\n", -200);
	// printf("%.1x\n", 0);
	// printf("%.2x\n", 4);
	// printf("%.3X\n", 314);
	// printf("%.4x\n", -29);
	// printf("%.15X\n", -99);
	// printf("%.5p\n", -99);
	// printf("%.15p\n", -99);
	// printf("%.5%\n");
	// printf("%.%\n");
	// printf("\nTESTING -\n");
	// printf("%-2c\n", '0');
	// printf("%-1c\n", '0');
	// printf("%-c\n", '0');
	// printf("%c%-2c%c\n", 'a', 'b', 'c');
	// printf("%1s\n", "t");
	// printf("%-1s\n", "t");
	// printf("%-3s\n", "-");
	// printf("%2p\n", -1);
	// printf("%-2p\n", -1);
	// printf("%-3p\n", 77);
	// printf("%-1p\n", 77);
	// printf("%-10p\n", 77);
	// printf("%d\n", 0);
	// printf("%-1d\n", 0);
	// printf("%-2d\n", -15);
	// printf("%-4d%d\n", -15, 333);
	// printf("%-0d\n", 15);
	// printf("%-1d\n", 15);
	// printf("%-6d\n", 15);
	// printf("%-1u\n", 0);
	// printf("%-2u\n", -1);
	// printf("%-6u\n", -16);
	// printf("%-1x\n", 0);
	// printf("%-3x\n", -1);
	// printf("%-5x\n", 115);
	// printf("%-2X\n", -5);
	// printf("%-3X\n", 0);
	// printf("%-1X\n", 89);
	// printf("%-15X\n", 89);
	// printf("%-2%\n", 89);
	// printf("\nTESTING #\n");
	// printf("%#c\n", 'c');
	// printf("%#s\n", "test");
	// printf("%#d\n", -3);
	// printf("%#i\n", -3);
	// printf("%#u\n", 3);
	// printf("%#x\n", 0);
	// printf("%#x\n", -1);
	// printf("%x\n", -1);
	// printf("%#x\n", 9);
	// printf("%#x\n", 54);
	// printf("%#x\n", -93);
	// printf("%#X\n", 0);
	// printf("%#X\n", -5);
	// printf("%X\n", -5);
	// printf("%#X\n", -111);
	// printf("%#X\n", 222);
	// printf("%#X\n", 13);
	// printf("%#p\n", 13);
	// printf("%#%\n");
	// printf("\nTESTING (space)\n");
	// printf("% c\n", 'c');
	// printf("% s\n", "test");
	// printf("% 1s\n", "tst");
	// printf("%d\n", 0);
	// printf("% d\n", 0);
	// printf("%  2d\n", 0);
	// printf("% d\n", 56);
	// printf("% d\n", -87);
	// printf("% i\n", -1);
	// printf("% i\n", 13);
	// printf("% i\n", -77);
	// printf("% i\n", 999);
	// printf("% 3u\n", 333);
	// printf("% u\n", 3);
	// printf("% p\n", 999);
	// printf("% x\n", 999);
	// printf("% X\n", 999);
	// printf("% %\n");
	// printf("\nTEST END\n");
	return (0);
}